import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import path from 'node:path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@app': path.resolve(__dirname, 'src/app'),
      '@widgets': path.resolve(__dirname, 'src/widgets'),
      '@entities': path.resolve(__dirname, 'src/entities'),
      '@shared': path.resolve(__dirname, 'src/shared'),
      '@i18n': path.resolve(__dirname, 'i18n'),
    },
  },
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./src/test/setup.ts'],
    css: false,
    include: ['src/**/*.test.{ts,tsx}', 'app/**/*.test.{ts,tsx}'],
    exclude: ['node_modules', 'dist', 'backend', '.next'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov'],
      reportsDirectory: './coverage',
      include: [
        'src/shared/api/**/*.ts',
        'src/shared/data/**/*.{ts,tsx}',
        'src/shared/lib/websocket/**/*.ts',
        'src/entities/planet/lib/**/*.ts',
        'src/entities/mission/lib/**/*.ts',
        'src/entities/satellite/model/helpers.ts',
        'src/widgets/iss-tracker/lib/ecefToScene.ts',
        'src/widgets/iss-tracker/lib/SatelliteRenderer.ts',
        'src/widgets/iss-tracker/lib/useSatellitesStream.ts',
        'src/widgets/iss-tracker/ui/ConnectionStatusBadge.tsx',
        'app/sitemap.ts',
        'app/**/page.tsx',
      ],
      exclude: [
        '**/*.test.{ts,tsx}',
        '**/index.ts',
        'src/shared/lib/scene/**',
        'src/widgets/cosmos-scene/**',
        'src/widgets/hud/**',
        'src/widgets/lang-switcher/**',
        'src/widgets/mission-sim-panel/**',
        'src/widgets/missions-panel/**',
        'src/widgets/planet-panel/**',
        'src/widgets/sidebar/**',
        'src/widgets/time-controls/**',
        'src/widgets/iss-tracker/IssTrackerClient.tsx',
        'src/widgets/iss-tracker/ui/IssTracker.tsx',
        'src/app/**',
        'app/page.tsx',
        'app/layout.tsx',
        'app/error.tsx',
        'app/not-found.tsx',
        'app/manifest.ts',
        'app/robots.ts',
        'app/[locale]/page.tsx',
        'app/[locale]/layout.tsx',
        'app/[locale]/error.tsx',
        'app/[locale]/loading.tsx',
        'app/[locale]/not-found.tsx',
        'app/[locale]/missions/**',
        'app/[locale]/planets/page.tsx',
        'app/[locale]/planets/[slug]/opengraph-image.tsx',
      ],
      thresholds: {
        lines: 70,
        branches: 65,
        functions: 70,
        statements: 70,
      },
    },
  },
});
